# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_scorecard_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
