# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 05:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_auto_20171228_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
